### ISSUE TITLE
iOS - Done button doesn't close keyboard

### ISSUE THREAD

**Issue by donatellijl12** [zleao/zoft.MauiExtensions.AutoCompleteEntry#10]
On Android when I press the "done" button on the keyboard, the keyboard is closed. On iOS, this does not happen. Pressing "done" does nothing on iOS. 

There is no way to close the keyboard due to the other issue of clicking outside of the keyboard also not closing the keyboard. (https://github.com/zleao/zoft.MauiExtensions.AutoCompleteEntry/issues/9)

**Comment by zleao** [comment]
Fixed in version 3.0.1
