### ISSUE TITLE
My mistake, this can be deleted

### ISSUE THREAD

**Issue by mark00h** [zleao/zoft.MauiExtensions.AutoCompleteEntry#2]
My mistake, this can be deleted

**Comment by zleao** [comment]
Hello.
So, in the end, did it work for you?

**Comment by zleao** [comment]
Hmmm. I see that I also forgot to add in the readme file the `UseZoftAutoCompleteEntry` in the Maui builder.
I'll take note of that `builder.UseMauiCommunityToolkit()`. I think this enforcement comes from another library that I also created.
Thanks for using this library.
