### ISSUE TITLE
"Collection was modified; enumeration operation may not execute."

### ISSUE THREAD

**Issue by dg2k** [zleao/zoft.MauiExtensions.AutoCompleteEntry#5]
Impossible to get past the following error on start:

System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'

I understand this has to do with a kind of "circular binding" (perhaps not the right phrase) because the modified by adding FilteredList feeds to the binding??

Surely, there must be a workaround for this issue and wondering what you suggest. Otherwise this is a great contribution.

With thanks.

**Comment by zleao** [comment]
Hello,
Thanks for the feedback.
Could you provide a sample with that escribed problem, or the code that you are executing that is generating this error?

**Comment by dg2k** [comment]
Hello,
Please find a sample project downloadable from my OneDrive storage with the link at the end below.

```
Type in a bit faster in the AutoComplete Editor and an exception will be throw.
Error: System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'
```
------------------------------
net.70 project
Visual Studio Community 17.7.4

```
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.25951
 OS Platform: Windows
 RID:         win-x64
```
------------------------------

[Sample project file](https://1drv.ms/u/s!AlLAD5XYdzWn3K1uVYSliQ6ykZh7XA?e=Sr7zOZ)

**Comment by zleao** [comment]
Hello @dg2k 
Thanks for the sample.
I haven't been able to look at it yet. Sorry.
Just wantde to let you know that this is not forgotten, and I'll look at it when I find a bit a time.

**Comment by zleao** [comment]
Hello again.
In which platform was this problem occurring?

**Comment by noahbki** [comment]
Hi, I am also having this issue. Platform my end is Android, with .NET 7.

**Comment by donatellijl12** [comment]
I'm having this issue too. The control doesn't work for me on Android due to this error.

**Comment by donatellijl12** [comment]
This happens for me when calling .Clear() on the ObservableCollection that the control is bound to. 

I had to change to not using .Clear() and .AddRange() to solve this bug.

This code works for me:
```
[ObservableProperty]
private ObservableCollection<School> filteredList = new();

public Command<string> TextChangedCommand => new(FilterList);
private void FilterList(string filter)
{
        SelectedSchool = null;
        FilteredList = new();

        if (filter.Length >= 3)
        {
            FilteredList = new ObservableCollection<School>(AllSchools.Where(s => s.Name.ToLower().Contains(filter.ToLower())).Take(10));
        }
}
```

**Comment by zleao** [comment]
I've recently changed the sample to stop using the `AddRange` in the filtered list, and instead, set a new list instance, as @donatellijl12 described.
Closing this issue for now. Thanks for the feedback!
