### ISSUE TITLE
Server side filtering

### ISSUE THREAD

**Issue by donatellijl12** [zleao/zoft.MauiExtensions.AutoCompleteEntry#6]
I've found that this component doesn't work well when I am calling an API to get filtered results before updating the observable collection. Is that intended?

**Comment by zleao** [comment]
Hello. 
Sorry for the late reply.
Having a non-working situation was not intended :) but I can imagine that if there are delays in the filtering result while continuing to write something on the text box, might lead to inconsistent behaviors.
Question: do you have any kind of mechanism implemented to cancel a previous filter request that is still running, when starting a new filter call?

**Comment by donatellijl12** [comment]
I changed to client-side filtering so I didn't have this issue. I don't think I had a mechanism to cancel the previous filter request.
