### ISSUE TITLE
Is there a way to remove the X?

### ISSUE THREAD

**Issue by Zacharianel** [zleao/zoft.MauiExtensions.AutoCompleteEntry#7]
Hi @zleao ,

Thank you so much for producing this component. Really very useful. However, I have a problem that can perhaps be solved and for this reason I ask for your help.
When an element is selected, the classic X appears to cancel the selection just made. Would it be possible to delete it and disable this option?

Let me know

Thank you again

**Comment by gsgou** [comment]
ClearButtonVisibility="Never" is applied while first rendered but the x button is shown when editing in Windows
