### ISSUE TITLE
Hello, I edited your project and placed the AutoCompleteEntry element in my own ContentViews to add my properties (HeaderProperty, ListOfItemsProperty, TxtProperty). Unfortunately, I am solving a problem with the TextProperty property binding.

### ISSUE THREAD

**Issue by GranakPavel** [zleao/zoft.MauiExtensions.AutoCompleteEntry#8]
Hello, I edited Your project and placed the AutoCompleteEntry element in my own ContentViews to add my properties (HeaderProperty, ListOfItemsProperty, TxtProperty). Unfortunately, I am solving a problem with the TextProperty property binding.
NewPage1ViewModel is used on the NewPage1.xaml page, where in the constructor I set the default value this.Text01 = "The default value of the Text01 property when the VM is initialized";, unfortunately, this value is not written when the application starts in the required <controls:AutoCompleteEntryContentView Header="Vehicle brand:" Txt="{Binding Text01, Mode=TwoWay}" ListOfItems="{Binding ListItemText01, Mode=TwoWay}" ></controls:AutoCompleteEntryContentView>.
Unfortunately, binding to the Txt item is broken. The txt entry is set 2x when the project is started, the first time with the correct text from the VM and the second time as an empty string.
Can someone help me with this problem?
(google translator)

MauiAppAutoCompeteEntry.zip
https://drive.google.com/file/d/14APs_dURRwzPWWUnmTjUGzOQiAC_1O9w/view?usp=sharing

.Net 7
Tested on Samsung Xcover6 pro (Android 13) and Windows 11 (22H2)

**Comment by zleao** [comment]
Hello.
I've just updated the repo with a sample of a binding to Text, where the initial value is set in the VM constructor.
Could you check if this issue is still ongoing?

**Comment by zleao** [comment]
I'm closing this issue, due to lack of activity and because I cannot reproduce it.
Thanks!
