### ISSUE TITLE
iOS/Android - Tapping outside of the keyboard does not close the keyboard

### ISSUE THREAD

**Issue by donatellijl12** [zleao/zoft.MauiExtensions.AutoCompleteEntry#9]
On both iOS and Android, whenever I tap outside of the keyboard, the keyboard does not close. This is not a big deal on Android because the done button and the built in down arrow both work to close the keyboard. However, on iOS, there is no way to close the keyboard due to the issue of the done button also not working (https://github.com/zleao/zoft.MauiExtensions.AutoCompleteEntry/issues/10).

**Comment by zleao** [comment]
Fixed in version 3.0.1
